
"""fic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tn--TMYBid3SwB9h67O9tvr0ZNFSw3JW
"""



import streamlit as st
from PIL import Image
import numpy as np
import tensorflow as tf


@st.cache_resource
def load_model():
    model = tf.keras.models.load_model("D:/guvi/p3/fishimageclassification_full.h5")
    return model

model = load_model()


class_names = ['animal fish', 'animal fish bass', 'fish sea_food black_sea_sprat', 'fish sea_food gilt_head_bream', 'fish sea_food hourse_mackerel',
               'fish sea_food red_mullet', 'fish sea_food red_sea_bream', 'fish sea_food sea_bass', 'fish sea_food shrimp', 'fish sea_food striped_red_mullet', 'fish sea_food trout']


st.title(" Fish Image Classifier")
st.write("Upload an image of a fish and the model will classify it.")


uploaded_file = st.file_uploader("Choose a fish image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Image", use_column_width=True)


    img_size = (224, 224)
    img = image.resize(img_size)
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)


    predictions = model.predict(img_array)
    predicted_class = class_names[np.argmax(predictions)]


    st.success(f"Predicted Class: **{predicted_class}**")